version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
  django_app:
    build: .
    command: gunicorn api_root.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    depends_on:
      - redis
    ports:
      - "8000:8000"
