# Generated by Django 5.0.7 on 2024-08-11 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0003_relatorio_callstaff_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callstaff',
            name='relatorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callstaffs', to='api_rest.relatorio'),
        ),
    ]
