# Generated by Django 5.0.7 on 2024-08-14 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0004_alter_callstaff_relatorio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='gender',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='id_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_view_sidebar',
        ),
    ]
