# Generated by Django 5.1 on 2024-08-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0009_remove_user_image_user_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('member_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(upload_to='profile_photos/', null=True, blank=True),
        ),
    ]
