# Generated by Django 5.1 on 2024-08-30 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0010_discordserver_alter_user_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discordserver',
            old_name='name',
            new_name='nameUser',
        ),
    ]
