# Generated by Django 5.1 on 2024-09-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0012_alter_user_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discordserver',
            name='nameUser',
        ),
        migrations.RemoveField(
            model_name='discordserver',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='discordserver',
            name='guild_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
