# Generated by Django 5.1 on 2024-09-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0013_remove_discordserver_nameuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='area',
            field=models.CharField(blank=True, choices=[('Jornalismo', 'Recursos Humanos'), ('Recrutamento', 'Recrutamento'), ('Eventos', 'Eventos'), ('Design', 'Design'), ('Movcall', 'Movcall'), ('Suporte', 'Suporte')], default='', max_length=100),
        ),
    ]
